class_name WavedashConstants

# Lobby Types
const LOBBY_TYPE_PUBLIC = 0
const LOBBY_TYPE_FRIENDS_ONLY = 1
const LOBBY_TYPE_PRIVATE = 2

# Broadcast Event Types
const JS_EVENT_LOBBY_MESSAGE = "LobbyMessage"

# Platform Types
const PLATFORM_WEB = "Web"

# Leaderboard Sort Methods
const LEADERBOARD_SORT_ASCENDING = 0
const LEADERBOARD_SORT_DESCENDING = 1

# Leaderboard Display Types
const LEADERBOARD_DISPLAY_TYPE_NUMERIC = 0
const LEADERBOARD_DISPLAY_TYPE_TIME_SECONDS = 1
const LEADERBOARD_DISPLAY_TYPE_TIME_MILLISECONDS = 2

# UGC Item Types
const UGC_TYPE_SCREENSHOT = 0
const UGC_TYPE_VIDEO = 1
const UGC_TYPE_COMMUNITY = 2
const UGC_TYPE_GAME_MANAGED = 3
const UGC_TYPE_OTHER = 4

# UGC Visibility
const UGC_VISIBILITY_PUBLIC = 0
const UGC_VISIBILITY_FRIENDS_ONLY = 1
const UGC_VISIBILITY_PRIVATE = 2

# API Call Result Codes (HTTP Status Codes)
const RESULT_OK = 200
const RESULT_ERROR = 400
const RESULT_NOT_FOUND = 404
const RESULT_UNAUTHORIZED = 401
const RESULT_FORBIDDEN = 403
const RESULT_INTERNAL_SERVER_ERROR = 500
const RESULT_BAD_REQUEST = 400
const RESULT_UNPROCESSABLE_ENTITY = 422
const RESULT_TOO_MANY_REQUESTS = 429
const RESULT_SERVICE_UNAVAILABLE = 503